### ISSUE TITLE
Confusing UX : Contact vs Place vs People/Person

### ISSUE THREAD

**Issue by estellecomment** [medic/medic#1772]
In the UI, the term "Contact" sometimes means "People and places", and sometimes means "Person attached to a place" (e.g. primary contact, contact for a user).

Possible solution : 
- In the first screenshot, in blue are the places we can use "People and Places", in orange "Places", in green "People". No use of "Contact". Change the icon of "People and Places" to show a person and a building.
  We could also split People and Places into two separate tabs. Unless there's a reason we want them together?
- In the second screenshot, remove the concept of a separate contact, and just have a form that fills in contact info for this user (how we save it in the db can stay the same).

![screen shot 2015-12-17 at 10 59 50](https://cloud.githubusercontent.com/assets/911434/11866929/40f22586-a4ae-11e5-8df7-ae18b5c4a002.png)
![screen shot 2015-12-17 at 11 15 55](https://cloud.githubusercontent.com/assets/911434/11867221/ed266afa-a4af-11e5-99e4-58759e242d86.png)

**Comment by abbyad** [comment]
@amandacilek the app has been updated since then... do you see this as a problem? If so are there any recommendations that you would like to make? Otherwise feel free to close this issue.

**Comment by amandacilek** [comment]
> In the first screenshot, in blue are the places we can use "People and Places", in orange "Places", in green "People". No use of "Contact". Change the icon of "People and Places" to show a person and a building.

I think most of this is obsolete. Yes, we do still use the word "contacts" throughout, but I think we use it because it is generic and flexible enough to apply to any configuration of the app. The name of the tab itself is configurable, the wording on the "Add new" button on the LHS is based upon the hierarchy structure, and there are no longer filters at the top. I am fine with the text at the end of the LHS remaining "No more contacts" and I am fine continuing to use the term "Primary contact".

> We could also split People and Places into two separate tabs. Unless there's a reason we want them together?

I know that this has been explored in the past, and I'm not saying we wouldn't ever want to explore it in the future...but right now I think it does us no favors to draw a harsh line between people and places. Some "places" like areas and families are in a grey area where they are more just groups of people than they are a distinct geographical/political/architectural zone. Once we implement flexible hierarchy I think the lines will further blur.

> In the second screenshot, remove the concept of a separate contact, and just have a form that fills in contact info for this user (how we save it in the db can stay the same).

I am not sure what exactly the suggestion is here. @abbyad do you understand what Estelle is saying?

**Comment by abbyad** [comment]
Thanks for reconsidering the comments!

I think the comment about the second screenshot makes sense only if the profile for the person doesn't exist already in the People tab. As I understand it would be so that the "person" could be created at the same time as the "user".

**Comment by amandacilek** [comment]
Dianna says not as confusing as it was before, if it comes back up it can be a new ticket but no need to hang on to this old one. Closing this ticket.
