### ISSUE TITLE
When logging in as a different user, the language of the previous user still shows

### ISSUE THREAD

**Issue by estellecomment** [medic/medic#3279]
Spotted on barefoot. 

Log in as admin (language : english)
Log out
Log in as < user > (language : hindi)
Expected : hindi, shown : english

It also works the other way round, < user > then admin.
If I clear all site data and log back in I see language properly. 
Going to user settings and re-saving the settings without changes (e.g. for < user >, the language is set as Hindi, even though English is displayed, so resave that) successfully changes the display language.

**Comment by nice-snek** [comment]
hi frand @browndav, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by browndav** [comment]
Scheduling.

**Comment by SCdF** [comment]
Uhm… this seems to literally be because the language is never changed except when you save the user model.

I guess this hasn't come up much because in real world scenarios people are rarely swapping languages on the same computer / browser.

**Comment by SCdF** [comment]
OK I misread the code: we are setting it on login, we're just using a different function.

The _actual_ [problem](https://geekwhisperin.files.wordpress.com/2009/09/bug-vs-feature.jpg) is that we cache the language in a cookie, instead of checking the user settings each time. I imagine we do this for performance?

This also means another [bug](https://geekwhisperin.files.wordpress.com/2009/09/bug-vs-feature.jpg) would be:
 - Have language set to Foo, open app in two browsers
 - Change language in one browser
 - Note that language doesn't change in the other

I've created a PR that just drops the use of a cookie: https://github.com/medic/medic-webapp/pull/3345

We don't appear to be caching UserSettings (though I could be wrong). Since we watch `_changes` we have the ability to cache a small set of static documents pretty easily. This would reduce the worry about checking documents like this, especially ones so critical as this one.

**Comment by SCdF** [comment]
@garethbowen over to you. Your thoughts about relying on UserSettings would also be welcomed.

**Comment by garethbowen** [comment]
Big long braindump on the PR - happy to discuss in person.

**Comment by SCdF** [comment]
OK I'm going to drop this one.

I have now spent too much time on this, relative to my understanding of its importance. Someone else is welcome to pick it up if they want, but I'm not feeling it. I was hoping it would be a quick win, but it got to yak shave territory very quickly, and there are more important pieces of work to do IMO.

Brain dump:
 - We don't want to get rid of the language cookie for performance reasons. Fair enough.
 - Instead, we should continue to use the language cookie, as well as scoping it to the user's name (using the Session, hold that thought), as well as make sure that when we boot we refresh the cookie if required (hold this thought as well), in case it has changed on another system / an admin changed it / whatever
 - `Language()` is used in various places to get the language, but it *also* sets the cookie if it's not already set. It is not apparent externally if it's had to do this or not, which means you don't know if you've already definitely got the freshest.
 - So we should change that so that when it's used in all the places it's used just to find out the language it still works, but also so we can tell if it's already had to load the UserSettings file so our code isn't cluelessly doing it twice
 - Then when we boot up the language in inbox.js we can boot it up, and then async also refresh it if we think we might need to
 - That UserSettings file should also be cached, because it gets casually loaded all over the place and it's unlikely to change much
 - Which involves using the Cache, which is based on callbacks (because you can have more than one listener?), except UserSettings wants promises, so bridge that
 - Except when you ask UserSettings you need to establish the session user, which according to the current code may not exist and so should error (though it's unclear if this can ever happen, or if in fact the session user ever changes, and thus explain why it gets looked up fresh every time, so maybe look into that too), so you have not create the cache until you've asked for it once.
 - Except: if you think the session can be wrong sometimes, that also implies it can be different sometimes, which means you might want to dig in and work out if you can really cache it or not
 - Also, fix all the unit tests you broke because they expect certain services that you've moved around
 - Also, I probably got something wrong here

**Comment by garethbowen** [comment]
Not a priority.

**Comment by garethbowen** [comment]
This has been fixed with recent work to fix other issues with setting locale on login. Closing.
