### ISSUE TITLE
Sentinel marks reports with the sys.facility_not_found error before it searches and looks for the contact

### ISSUE THREAD

**Issue by henokgetachew** [medic/medic#3543]
Version of the webapp that was being tested: 2.12.0-beta.5
Instance: clone-kilifikids-kaiti
This was the test message that was sent and look at an earlier revision:
![image](https://user-images.githubusercontent.com/3198821/27075850-1378b33a-5034-11e7-81b6-c2d95b369faf.png)

After a few minutes, the document gets updated again and the error is removed and the contact was saved into the doc.
![image](https://user-images.githubusercontent.com/3198821/27075954-6981e940-5034-11e7-9ae6-2752f0ef954b.png)
Marking the document with that specific error before searching the contacts to check whether the contact exists or not does not make sense.  The extra write operation also seems like it's not required and removing it might improve performance.

**Comment by garethbowen** [comment]
This is actually by design, but I agree it's a terrible design. I'm going to change this to a performance issue because it is actually working as intended.

**Comment by sglangevin** [comment]
@garethbowen @dianabarsan will this be solved by the new ordering of Sentinel transitions? If not, then it should be reviewed as part of #4128.

**Comment by garethbowen** [comment]
It's actually not sentinel doing this, it happens in the sms endpoint automatically, and then sentinel removes it if the facility actually is found. It's something we should clean up because it's confusing.

**Comment by sglangevin** [comment]
I also think it would be cool if reports had no dot until we determined if there are any errors. Right now they sometimes display in the UI with red dots until processed by Sentinel, which finds the facility and then the dot becomes green. Even having it the other way around would be more helpful (assume it's correct until proven otherwise).

**Comment by garethbowen** [comment]
@dianabarsan I'm thinking that the new synchronous sentinel will mean we can resolve this, right?

**Comment by dianabarsan** [comment]
Yes, because `update_clinics` will run over the document before the initial save and remove `sys.facility_not_found` error (which is still added by the API `record-utils` controller).

**Comment by garethbowen** [comment]
Awesome. Do you think it'd be worth updating `record-utils` to not do that, given that `update_clinics` will do it before save?

**Comment by dianabarsan** [comment]
We could do that and change `update_clinics` to add the error in case the contact is not found. 
It would be overall cleaner (as you'd only have one component juggling the magic string `sys.facility_not_found` instead of 2 - one adding and one clearing). 
I've also found another little bug in `update_clinics` so I'm likely to update it soon anyway.

**Comment by garethbowen** [comment]
Ok let's do it. The only change in behaviour I can think of is if the configuration disables `update_clinics` but in that situation all reports would have `facility_not_found` and I'm sure that's not the desired behaviour.

**Comment by garethbowen** [comment]
Ready for AT in `3543-facility-not-found`

**Comment by dianabarsan** [comment]
Please do not merge post AT, a shared library needs to be published and dependencies bumped on the branch.

**Comment by ngaruko** [comment]
LGTM @dianabarsan ..  Back to you for merging
