### ISSUE TITLE
If server is down, app cannot start

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#3986]
# Observed

1. configure and log in to app on mobile, over local network (`192.168.…`)
2. close app
3. disable wifi on phone
4. enable 3g on phone

I _think_ this will reliably simulate what would happen if a server was down...

<img width="418" alt="screen shot 2017-10-23 at 10 25 00" src="https://user-images.githubusercontent.com/191496/31876744-7b990112-b7dc-11e7-91fb-634cf1db0fd0.png">

# Expected

App should load.  I suspect this will be hard to handle, as the ISP seems to serve the `504`.

If the 504 can't be handled in browser, then the android wrapper should do something clever.

**Comment by garethbowen** [comment]
It's hard to tell but it looks like you were being redirected to the login page which should only happen if your session cookie timed out which shouldn't happen in production where we set a large timeout.

I'm wondering if the login screen should be appcached (maybe together or separately from the main app) so it can load even if you're offline. But maybe that's more annoying because you'll type in your user/pass before finding out you can't log in anyway...

**Comment by garethbowen** [comment]
Related: #1419

**Comment by newtewt** [comment]
Not getting a 504  but still getting an error. The app is unusable if the device can't connect to the server when starting. The same steps listed above were used in getting the error below. 

![Screenshot_20190516-200908](https://user-images.githubusercontent.com/10531066/57880608-27c9c580-77ed-11e9-8c81-746edf6596c8.png)

**Comment by kennsippell** [comment]
I believe the appropriate webapp changes are in place to load while completely offline through the browser - but XWalk is giving up due to this ERR_NAME_NOT_RESOLVED issue for in-app users. 

I've attempted to stub out our custom [Load Error Handler](https://github.com/medic/medic-android/blob/master/src/main/java/org/medicmobile/webapp/mobile/EmbeddedBrowserActivity.java#L417) without success.

This bug basically means we have an offline-first app that can't load while offline - so it seems pretty important to me. I'll continue my investigations. That said, with the state of the 3.5 release and that the remaining work likely isn't in the core webapp: we might consider removing this from the 3.5 release.

**Comment by newtewt** [comment]
I'll confirm on 3.4 and report back today.

**Comment by newtewt** [comment]
@kennsippell  In 3.4 the app loads fine. I disconnected from WiFi and have no cell service. I closed the app and restarted it loads fine. Restarted the phone and loaded the app ok as well. I don't think we can bump this from 3.5.

**Comment by garethbowen** [comment]
I agree, if this has indeed regressed from 3.4.0 it's a blocker in 3.5.0.

I can't see why it would be a Crosswalk issue - I would have expected the SW to catch it and respond before it got out to Android. Is it possible it's an issue with older versions of Chrome?

**Comment by garethbowen** [comment]
Ready for AT on `3986-cache-rewrite`

**Comment by newtewt** [comment]
Does this need to be tested with the android app changes as well or should the current app work with these changes? 

@kennsippell  @garethbowen

**Comment by kennsippell** [comment]
@newtewt The change in medic-android is a bit of an optimization, but shouldn't be required to validate this flow. For now, let's focus on the webapp change `3986-cache-rewrite` without any changes to the android app. Important to confirm that 3.5 works fine as an offline app with the existing app and that no container upgrade is required.

**Comment by garethbowen** [comment]
@newtewt Ready for AT in `3986-cache-rewrite`

**Comment by newtewt** [comment]
I'm able to use the app when offline. I'm able to close and reopen when I'm offline as well. This is working now as expected.
