### ISSUE TITLE
Removes changes watching for online users to improve performance

### ISSUE THREAD

**Issue by SCdF** [medic/medic#4327]
Currently, online users are (on semi-large instances) unusable because:
 - The `_changes` feed watching in the `Changes` service watches and downloads every change to the database in full (eg `include_docs: true`)
 - The UI then live-responds based on the page you're on and updates accordingly (changing the value of a form, adding / removing reports from the LHS etc)

On semi-large instances this is both way to much data to constantly download, and way too many UI updates to be performant.

NB: this is still fine for offline users, as they don't see as much data, and they already need the data on their device anyway.

Instead, we should:
 - Go through all usages of the `Changes` service and work out how to replace the functionality in a minimal way. For example, LHS lists should have a button you can press to refresh the search (this may already work this way).
 - If each usage can be replaced in a nice way make those changes and disable the Changes service for online users.
 - If there are instances where we still need some kind of change watching (detecting an upgrade comes to mind) we may need to build a less generic / more efficient changes service that we can use to know if there are new pieces of information for a particular view / use case, but not the whole contents until eg. someone refreshes. This would be in api. We can cross that bridge if we feel like we come to it.

**Comment by SCdF** [comment]
So two options for things like app updates:
 - still follow the _changes feed but don't include_docs. This lets you detect changes based on doc name, which works for app updates but maybe not for other things
 - write an api endpoint that you can follow which *does* follow the _changes feed with include_docs internally and , and based on business logic occasionally passes on change actions (eg "an update is available", "there is a new report")

**Comment by amandacilek** [comment]
Just to clarify, when we're talking about "changes", we mean changes from external sources (other people), right? So any change the online user makes themselves obviously is still instantly reflected in the UI immediately right?

If the current rule that is causing us problems is "check for changes constantly" could we modify it to be more like a mail inbox, and say "check for changes once every five minutes"? My gut feeling is that making the sync a little lagged, but still automatic, would be better than requiring users to manually click a refresh button.

cc @diannakane

**Comment by garethbowen** [comment]
> Just to clarify, when we're talking about "changes", we mean changes from external sources (other people), right? So any change the online user makes themselves obviously is still reflected in the UI immediately right?

Technically speaking, no, there is no distinction between your changes and someone else's. However, when you do things like submitting a form the page changes, which I think will kick off a search and show your changes so I think in effect any change you make will be shown right away (though we need to test to make sure).

> If the current rule that is causing us problems is "check for changes constantly" could we modify it to be more like a mail inbox, and say "check for changes once every five minutes"?

It's definitely worth thinking about but it would potentially need quite a lot of code to pull this off because every page would need to implement the timer and understand what to refresh every _x_ minutes.

We might be able to extend the Changes service so it batches changes together which would simplify the implementation significantly because all the code would be in one place.

**Comment by kennsippell** [comment]
Some of these suggested changes sound like they might benefit offline users by improving performance, battery life, and reducing code complexity.

> If each usage can be replaced in a nice way make those changes and disable the Changes service for online users.

If these can be solved for online users, why not remove this code and make these changes for all users?  Here are a few supporting arguments as to how these same changes may benefit offline users:

* Given a scenario where the user goes to contacts tab > selects a contact > edits the contact. We are three screens deep and still processing, requerying, and redrawing changes on both hidden screens. Since this happens in parallel, it can impact the performance of the user's active tasks unnecessarily.
* The logic we have when a change occurs is often similar to "requery and redraw everything." In some cases, this may result in multiple seconds of high resource consumption (battery life) - many times with no resulting UI change. 
* Watching for changes adds significant code complexity and qa scenarios.

**Comment by garethbowen** [comment]
It would definitely help performance, though I'm not sure how much. My understanding is that most restricted users push data much more than they pull. That means the changes feed fires mostly when they've done something in which case it's really important the UI is updated everywhere. Supervisors are in a grey area where they pull quite a lot so it may make sense at this level.

**Comment by dianabarsan** [comment]
Ready for AT on `4327-admin-changes`

This branch changes the way the app behaves when the logged in user has an online role.

Rather than watching changes with `include_docs` and having the app be 100% responsive to external changes, we are now watching changes without `include_docs`. 

The interface should still be updated by the direct actions of the logged user performed **in the same tab** (for example adding a new report yourself should immediately display that report in the LHS list). 

Additionally, certain external updates should be reflected in the app like: 
- the popup when settings/app updates happen should still appear in real time
- changes + additions + deletions of forms should work as before
- changes in translations should work as before
- new languages being added in the admin area should work as before
- the upgrade page should work as before
- user role updates should still trigger the reload form
- zscore charts should be updated
- updates to the report you are viewing 
- updates the contact you are viewing (this does not include displaying new reports/children, just updates made directly to the contact itself)
- deletions should be reflected in lists in real time

Offline users should not be affected by this change. 

For AT, make sure that the longpoll `_changes` request does not have an `include_docs=true` param and incoming changes do not carry a `doc` property. The app should be responsive to the actions you perform yourself and to specific external actions (listed above). 
The unread doc counts (the red badges that appear in the header above the `Reports` and `Messages` links) are incremented/decremented by your actions and are fully refreshed once every 5 minutes. 

The place hierarchy (which is used for filtering reports) is updated by your changes, but not by external changes. This is the one unfortunate case where only a full page refresh will get you the updated list. 
The place hierarchy way of functioning is under question and is possible to change (https://github.com/medic/medic/issues/4423), so we have agreed to leave this as is for the time being.

**Comment by ngaruko** [comment]
LGTM.
