### ISSUE TITLE
Replace appcache with a service worker cache

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#4713]
Appcache has been deprecated so one day it'll just stop working. To prepare for the future we should switch to using service workers. This will also give us the benefit of more reliable updates and if we're careful will reduce the amount of code that has to be downloaded on update.

**Comment by garethbowen** [comment]
Translations for "downloading app..." are available here: https://docs.google.com/spreadsheets/d/1FB0o9hXeyWrxNJwq4KmOhtOvuSUfxRIq_JlygdVp-Yk/edit#gid=0

**Comment by garethbowen** [comment]
@kennsippell Is this ready for AT now?

**Comment by kennsippell** [comment]
Yep!

**Comment by ngaruko** [comment]
Does this need any AT-ing from the QA's end @kennsippell ?

**Comment by kennsippell** [comment]
@ngaruko In the PR (https://github.com/medic/medic/pull/5190) there is a section `Scenarios I Tested`. If you're happy with that level of testing, skip it. Or if you'd like to run a sanity check, you can run through those again.

**Comment by ngaruko** [comment]
The incognito mode does not seem to work in Firefox (`private window`) with the following errors @kennsippell 
Would this be related to this issue?
![image](https://user-images.githubusercontent.com/6979995/57370349-13ca0680-71e4-11e9-94e3-87a9d53d67f8.png)

**Comment by kennsippell** [comment]
@ngaruko  Yes -- Firefox private browsing mode doesn't support service workers.

> In Firefox, Service Worker APIs are hidden and cannot be used when the user is in private browsing mode.

https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers

I don't think this is new though. The error that is displaying has changed, but we can't bootstrap in a private window on Firefox on v3.3 either. Due to the second error causing us to "Failed to open indexedDB, are you in private browsing mode?"

**Comment by ngaruko** [comment]
Thanks @kennsippell - Will close this. Related PR already closed.
