### ISSUE TITLE
Move feedback docs to users' meta dbs

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#4898]
When there is an exception client-side, a doc is created in the main shared DB containing details, with `"type": "feedback"`.  These docs are read-only, and only of interest to system administrators.  It may be more efficient for clients, and change view filtering, if these docs were stored in users' personal meta dbs instead of in the main db.

Related:

* https://github.com/medic/couch2pg/issues/7 - *[couch2pg] Consider filtering out feedback docs from the medic database*
* #4834 - *Move `medic-client/feedback` view into admin ddoc*

**Comment by kennsippell** [comment]
In case you were wondering how many feedback docs there are for some of our projects. The number is definitely significant. Do we replicate these docs to users? 

database | sum
-- | --
musoapp | 34,451
livinggoods-ke | 41,677
livinggoods-ug | 782,368
moh_kenya_siaya | 25,159
brac-ug | 1,737,504

Thanks to @michaelkohn for pulling these numbers.

**Comment by garethbowen** [comment]
No we don't replicate them down to users, but we do need them to replicate up to the server.

The numbers should not be that high and it indicates a bug in either the software or the configuration. @michaelkohn Is there any quick way to work out what errors are being thrown most often?

**Comment by michaelkohn** [comment]
Here are the top messages across the projects mentioned above (plus one more).   Full details can be found [here](https://docs.google.com/spreadsheets/d/1OMvqi70JbulaMi17Dex2SVZwJpPM9E8TOp0u8OfOyyQ/edit#gid=300719531)


info/message | Count
-- | --
Uncaught TypeError: Cannot read property 'handleAndroidBack' of undefined | 2,100,422
Uncaught TypeError: Cannot call method 'handleAndroidBack' of undefined | 318,135
Uncaught Error: Could not resolve 'undefined' from state 'home' | 92,152
  | 29,053
Uncaught TypeError: Cannot read property 'body' of undefined | 18,397
Uncaught TypeError: Cannot read property 'scrollIntoView' of undefined | 13,883
Uncaught TypeError: Cannot read property 'length' of undefined | 13,834
Uncaught Error: Could not resolve 'undefined' from state 'about' | 9,651
Uncaught TypeError: document.querySelectorAll(...).forEach is not a function | 6,288
Uncaught Error: [$injector:unpr] Unknown provider: AndroidApiProvider <- AndroidApi http://errors.angularjs.org/1.5.5/$injector/unpr?p0=AndroidApiProvider%20%3C-%20AndroidApi | 6,167
Uncaught TypeError: Cannot read property '_id' of null | 2,991
Uncaught Error: Could not resolve 'undefined' from state 'tasks.detail' | 2,200
Uncaught TypeError: Cannot call method 'scrollIntoView' of undefined | 1,907
Uncaught InvalidStateError: Failed to execute 'index' on 'IDBObjectStore': The transaction has finished. | 1,478
Uncaught TypeError: fieldset:disabled input, fieldset:disabled select, fieldset:disabled textarea, input:disabled, select:disabled, textarea:disabled is not a function | 1,227
Uncaught TypeError: Cannot read property 'clone' of null | 1,138
Uncaught Error: Cannot transition to abstract state 'tasks' | 923
Uncaught ReferenceError: console is not defined | 506
Uncaught Error: Could not resolve 'undefined' from state 'contacts.detail' | 334
Error: [$rootScope:inprog] $digest already in progress http://errors.angularjs.org/1.5.5/$rootScope/inprog?p0=%24digest | 315
Uncaught exception: Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting! | 205
Uncaught Error: Could not resolve 'undefined' from state 'analytics.targets' | 180
Uncaught TypeError: Cannot call method 'clone' of null | 142
Uncaught Error: Could not resolve 'undefined' from state 'contacts.addChild' | 109

**Comment by SCdF** [comment]
Those top two are really weird. We haven't had or referenced anything called `handleAndroidBack` since 2016. It was dropped in ce93efb5527ca9ded79fbdd4b83e2db6c6c1084a.

**Comment by michaelkohn** [comment]
There was no date filter on the query, so the grid above includes everything from the beginning of each project.

**Comment by garethbowen** [comment]
@michaelkohn Is it possible to filter down to just the last 12 months or so?

**Comment by michaelkohn** [comment]
Here you go @garethbowen .... I re-ran the queries with a date filter of `>= '2018-01-01'`.

The spreadsheet [here](https://docs.google.com/spreadsheets/d/1OMvqi70JbulaMi17Dex2SVZwJpPM9E8TOp0u8OfOyyQ/edit#gid=1979929895) has the breakdown by partners.  

info/message | Count
-- | --
Uncaught   TypeError: Cannot read property 'handleAndroidBack' of undefined | 581,624
Uncaught   Error: Could not resolve 'undefined' from state 'home' | 50,836
Uncaught   TypeError: Cannot read property 'body' of undefined | 18,362
Uncaught   TypeError: Cannot call method 'handleAndroidBack' of undefined | 14,158
Uncaught   TypeError: Cannot read property 'length' of undefined | 13,596
  | 13,526
Uncaught   TypeError: Cannot read property 'scrollIntoView' of undefined | 7,572
Uncaught   Error: Could not resolve 'undefined' from state 'about' | 6,433
Uncaught   TypeError: document.querySelectorAll(...).forEach is not a function | 6,286
Uncaught InvalidStateError: Failed to execute 'index'   on 'IDBObjectStore': The transaction has finished. | 1,475
Uncaught   Error: Could not resolve 'undefined' from state 'tasks.detail' | 1,334
Uncaught TypeError: fieldset:disabled input,   fieldset:disabled select, fieldset:disabled textarea, input:disabled,   select:disabled, textarea:disabled is not a function | 988
Uncaught   TypeError: Cannot read property 'clone' of null | 238
Uncaught   Error: Could not resolve 'undefined' from state 'contacts.detail' | 213
Uncaught   Error: Could not resolve 'undefined' from state 'analytics.targets' | 114
Uncaught   TypeError: Cannot read property '_attachments' of undefined | 87
L’objet   ne gère pas la propriété ou la méthode « forEach » | 76
Uncaught   Error: Could not resolve 'undefined' from state 'contacts.addChild' | 61
Script   error. | 57
Uncaught   Error: Could not resolve 'undefined' from state 'reports.detail' | 33
Uncaught   Error: Could not resolve 'undefined' from state 'error' | 28
Uncaught   TypeError: Cannot read property '_id' of null | 26
Uncaught   Error: Could not resolve 'undefined' from state 'messages.detail' | 22
Uncaught   TypeError: Cannot read property 'outerHTML' of undefined | 20
Uncaught   TypeError: Cannot call method 'scrollIntoView' of undefined | 19
Uncaught TypeError:   angular.element(...).injector(...).get(...).v1.simprintsResponse is not a   function | 15
Uncaught FormLogicError: Could not evaluate:   selected(../dob_method,'calendar'), message: Cannot read property   'ownerDocument' of undefined | 15
Object   doesn't support property or method 'forEach' | 14
Uncaught FormLogicError: Could not evaluate:   selected(../vaccines, 'other'), message: Cannot read property 'ownerDocument'   of undefined | 13
Uncaught   Error: Could not resolve 'undefined' from state '' | 10
Uncaught   TypeError: Cannot read property 'toString' of undefined | 7
Uncaught   FormLogicError: Could not evaluate: concat(../../contact/name, ' Family'),   message: Failed to execute 'evaluate' on 'Document': The string   'concat('Ñ\!'è! \"è#9ìčè', " Family")' is not a valid XPath   expression. | 7
Uncaught   TypeError: Cannot read property 'seq' of null | 6
Uncaught   TypeError: Cannot read property 'createObjectStore' of undefined | 6
Uncaught   TypeError: Cannot read property 'balance' of null | 6
Uncaught   TypeError: Cannot read property '0' of undefined | 6
Unable   to get property 'top' of undefined or null reference | 5
Uncaught   Error: Could not resolve 'undefined' from state 'reports.add' | 3
NotFoundError: The operation failed because the   requested database object could not be found. For example, an object store   did not exist but was being opened. | 3
Uncaught   TypeError: Cannot read property 'error' of null | 2
Uncaught FormLogicError: Could not evaluate:   concat(../../contact/name, ' Family'), message: Failed to execute 'evaluate'   on 'Document': The string 'concat(redacted, "   Family")' is not a valid XPath expression. | 2
Uncaught DataCloneError: Failed to execute 'put' on   'IDBObjectStore': An object could not be cloned. | 2
Uncaught   TypeError: Cannot read property 'format' of undefined | 1
Uncaught   TypeError: Cannot call method 'clone' of null | 1
Uncaught   SyntaxError: Unexpected token  in JSON at position 4 | 1
Uncaught   SyntaxError: Unexpected token  in JSON at position 4 | 1
Uncaught   SyntaxError: Unexpected token  in JSON at position 4 | 1
Uncaught   SyntaxError: Unexpected token in JSON at position 3 | 1
Uncaught   SyntaxError: Unexpected token  in JSON at position 3 | 1
Uncaught   SyntaxError: Unexpected token in JSON at position 22 | 1
Uncaught   SyntaxError: Unexpected token  in JSON at position 15 | 1
Uncaught   SyntaxError: Unexpected token  in JSON at position 11 | 1
Uncaught   SyntaxError: Unexpected token in JSON at position 10 | 1
Uncaught   Error: unexpectedly reached end of input: � | 1
Uncaught   Error: unexpectedly reached end of input: @ | 1
Uncaught   Error: unexpectedly reached end of input: ¿ | 1
allocation   size overflow | 1
Grand   Total | 717,321

**Comment by garethbowen** [comment]
I've raise a new issue to go through those errors - thanks Michael!

**Comment by garethbowen** [comment]
AT:
- Make sure feedback docs are stored in the users meta db not the main medic db.
- Make sure the feedback docs eventually replicate into a new shared users meta db based on a configurable cron job.
- Make sure you can view feedback on the Admin > Export > Feedback page and that the export button works as expected.

**Comment by newtewt** [comment]
@wtekeu  a couple things I found while testing. 

As I continue to upload settings with different changes. I see that the number of replications grows. 

To reproduce:
Configure replications like this
```
 "replications": [
    {
      "fromSuffix": "user-[^\\-]+-meta",
      "toSuffix": "nick",
      "text_expression": "",
      "cron": "* * * * *"
    }
  ]
```
```
 "replications": [
    {
      "fromSuffix": "user-[^\\-]+-meta",
      "toSuffix": "red-nick",
      "text_expression": "",
      "cron": "* * * * *"
    }
  ]
```
Now you'll see similar to below where the logs are showing multiple replications even after the settings have been changed. 
```
2019-04-11 15:46:00 INFO: Replicating docs from "medic-user-ac1-meta" to "medic-meidic-medic-medic" 
2019-04-11 15:46:00 INFO: Replicating docs from "medic-user-ac2-meta" to "medic-meidic-medic-medic" 
2019-04-11 15:46:00 INFO: Replicating docs from "medic-user-admin-meta" to "medic-meidic-medic-medic" 
2019-04-11 15:46:00 INFO: Replicating docs from "medic-user-ac1-meta" to "medic-second-medics" 
2019-04-11 15:46:00 INFO: Replicating docs from "medic-user-ac2-meta" to "medic-second-medics" 
2019-04-11 15:46:00 INFO: Replicating docs from "medic-user-admin-meta" to "medic-second-medics" 
2019-04-11 15:46:00 INFO: Replicating docs from "medic-user-ac1-meta" to "medic-meidic-medic-medic" 
2019-04-11 15:46:00 INFO: Replicating docs from "medic-user-ac2-meta" to "medic-meidic-medic-medic" 
2019-04-11 15:46:00 INFO: Replicating docs from "medic-user-admin-meta" to "medic-meidic-medic-medic" 
2019-04-11 15:46:00 INFO: Replicating docs from "medic-user-ac1-meta" to "medic-red-nick" 
2019-04-11 15:46:00 INFO: Replicating docs from "medic-user-ac2-meta" to "medic-red-nick" 
2019-04-11 15:46:00 INFO: Replicating docs from "medic-user-admin-meta" to "medic-red-nick" 
2019-04-11 15:46:00 INFO: Replicating docs from "medic-user-ac1-meta" to "medic-nick" 
2019-04-11 15:46:00 INFO: Replicating docs from "medic-user-ac2-meta" to "medic-nick" 
2019-04-11 15:46:00 INFO: Replicating docs from "medic-user-admin-meta" to "medic-nick" 
```

A second issue. Not a huge one since we don't crash but maybe we add a default if nothing is specified?
Configure replications like this. With no toSuffix

```
 "replications": [
    {
      "fromSuffix": "user-[^\\-]+-meta",
      "toSuffix": "",
      "text_expression": "",
      "cron": "* * * * *"
    }
  ]
```

You'll see this error. 
```
2019-04-11 15:13:00 ERROR: uncaughtException: Invalid replication config with text expression = '' and cron = '* * * * *'
Error: Invalid replication config with text expression = '' and cron = '* * * * *'
    at replications.reduce (/home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/src/schedule/replications.js:51:15)
    at Array.reduce (<anonymous>)
    at Object.execute (/home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/src/schedule/replications.js:49:18)
    at async.series.cb (/home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/src/schedule/index.js:51:28)
    at /home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/node_modules/async/dist/async.js:3880:24
    at replenish (/home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/node_modules/async/dist/async.js:1011:17)
    at iterateeCallback (/home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/node_modules/async/dist/async.js:995:17)
    at /home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/node_modules/async/dist/async.js:969:16
    at /home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/node_modules/async/dist/async.js:3885:13
    at /home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/node_modules/async/dist/async.js:473:16 Error: Invalid replication config with text expression = '' and cron = '* * * * *'
    at replications.reduce (/home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/src/schedule/replications.js:51:15)
    at Array.reduce (<anonymous>)
    at Object.execute (/home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/src/schedule/replications.js:49:18)
    at async.series.cb (/home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/src/schedule/index.js:51:28)
    at /home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/node_modules/async/dist/async.js:3880:24
    at replenish (/home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/node_modules/async/dist/async.js:1011:17)
    at iterateeCallback (/home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/node_modules/async/dist/async.js:995:17)
    at /home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/node_modules/async/dist/async.js:969:16
    at /home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/node_modules/async/dist/async.js:3885:13
    at /home/newtewt/.horticulturalist/deployments/medic-sentinel/md5-YnOK0yPlz10XlxNEDaLvw==/node_modules/async/dist/async.js:473:16
```

**Comment by wtekeu** [comment]
@newtewt 
1) it is replicating to different databases that is why it is doing it multiple times .. the target db name is the name of the main db to which the value of the field `toSuffix` is appended
2) I will ensure that `fromSuffix` and 'toSuffix` are not empty or else produce/log an error.
What do you think?

**Comment by newtewt** [comment]
@wtekeu  for 1 would I would think that if I updated my settings on replications from `toSuffix: 'blah'` to `toSuffix:'blah1'` I would only see replications occur once right? Not a replication occurring for each setting that has been saved in previous time. Maybe I'm doing a poor job explaining via text and we can work out a time to get a call going.

**Comment by wtekeu** [comment]
@newtewt slack me whenever you can

**Comment by newtewt** [comment]
@wtekeu  with the latest changes the previous settings are retained if they are updated. I'm seeing that it continues to replicate to the previously defined database until I stop sentinel and restart it.

**Comment by newtewt** [comment]
@wtekeu this is good to merge. AT looks good.

**Comment by wtekeu** [comment]
@garethbowen you may want to merge your branch
