### ISSUE TITLE
User cannot logout while offline

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5183]
If the user is offline and selects "Log out", they get to an error page and when they reconnect they are online.

**Steps to reproduce**:

1. Launch the app
1. Login
1. Go offline
1. Click "Log out" and confirm "yes"
1. Land on app's error page
1. Reconnect to data and click "retry"

**What should happen**:
User should be logged out

**What actually happens**:
User is still logged in

Possible data security implications of not being able to logout and hide your data.
Currently the session cookie is HttpOnly so it can't be deleted in script.

**Comment by kennsippell** [comment]
I know of two ways to handle this:

1. Remove HttpOnly flag on the session cookie and then delete it in script on logout. In combination with #5082, this is reasonably secure but having the HttpOnly flag is a nice practice.
1. To keep the HttpOnly flag on the cookie, we can use the service worker created by #4713 to respond to a logout request with a response which clears the cookie.

Any preference?

**Comment by garethbowen** [comment]
Related: #3986 . We should make sure this is fixed at the same time.

**Comment by kennsippell** [comment]
As part of logging out offline, cache the login resources. Re discussion in #5219

**Comment by wtekeu** [comment]
@garethbowen , @kennsippell suggests the following:
"so when the user clicks 'logout' set a new cookie
and when the user logs in successfully, clear the cookie
and when the app loads -- in the logic which already redirects to the login page. also redirect if that cookie exists"
what do you think? Or preventing the user from doing anything as long as the cookie exists and he is offline (I believe we could use service worker for that)
Or we do nothing and just display a message explaining that it is not possible to logout while offline

**Comment by garethbowen** [comment]
That's ok, and may be the best we can do. I'm concerned because the browser will tell them they've logged out when really they haven't. Anyone with access to the device could find the session id and hijack it. This would be quite a sophisticated attack because you'd need to block internet access, hope the user logs out, access their device with dev tools, inspect the cookies, then inject the session cookie into your own request.

The alternatives are either a) leave it as it is, or b) change the cookie to be JS accessible. Option a is even less safe because if the user clicks logout while offline then the session cookie remains and all the attacker has to do is refresh the browser. Option b is less safe because then all session cookies are exploitable by JS injection.

So let's go with Kenn's suggestion. It'd be good if when the new cookie is detected we show the login page but also make a request to the server to logout which hopefully cleans up the old session cookie as soon as possible. You could even use a setInterval to retry the logout every 5 minutes until successful.

**Comment by kennsippell** [comment]
It would be great to understand the exact limits which prevent his from being able to handled through our service worker code.

**Comment by wtekeu** [comment]
The service worker fails to cache `DELETE /_session`.

I used the following config:
``` 
runtimeCaching: [{
      handler: 'networkFirst',
      urlPattern: '/_session',
      method: 'any',        
      options: {
        debug: true
      }
    }],
```
which produced the following line:
`toolbox.router.any("/_session", toolbox.networkFirst, {"debug":true});`

The `GET /_session` is cached:
<img width="1255" alt="Screen Shot 2019-03-11 at 10 45 28 AM" src="https://user-images.githubusercontent.com/1445164/54134593-a28df300-43ee-11e9-86f3-f74e95f50581.png">

Maybe we need another pair of eyes to review this.

**Comment by kennsippell** [comment]
I view this cookie-based psuedo-logout as a last resort, which we should pursue only if we can't achieve an actual logout through the service worker.

I believe that an actual logout may still be possible through the service worker. Have you tried creating a cacheable logout endpoint through api like we discussed?

**Comment by wtekeu** [comment]
Yes, I did try that and it failed to set the cookie

**Comment by kennsippell** [comment]
Super weird that it caches `GET` and not `DELETE` requests. DELETE is listed in the list of supported methods for sw-toolbox. https://googlechromelabs.github.io/sw-toolbox/api.html#expressive-approach

Sucks we can't manipulate cookies. Thanks for trying. I wonder if the Set-Cookie header was included in the list of headers in the cache.  I left some comments on your change.

**Comment by ngaruko** [comment]
LGTM

**Comment by wtekeu** [comment]
merged ... @kennsippell you may want to merge your branch
