### ISSUE TITLE
Offline users are caching 1.4MB of unused font files 

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5260]
Our current proposed service worker caches about 2.5MB of font files. Here is the current list of files and their sizes: 

Filename | Size (kB) 
-- | -- 
enketo-icons-v2.eot | 5 
enketo-icons-v2.svg | 10 
enketo-icons-v2.ttf | 5 
enketo-icons-v2.woff | 4  
FontAwesome.otf | 135  
fontawesome-webfont.eot | 166 
fontawesome-webfont.svg | 445 
fontawesome-webfont.ttf | 166 
fontawesome-webfont.woff | 99 
fontawesome-webfont.woff2 | 78 
NotoSans-BoldItalic.ttf | 291 
NotoSans-Bold.ttf | 416 
NotoSans-Italic.ttf | 280 
NotoSans-Regular.ttf | 415 

Summary of the font formats and the browsers/users they are intended for: https://transfonter.org/formats 

## Font Awesome (985kb) 

907kB potential savings -- the Webapp and modern browsers all use the `woff2` format (78 kb). Other formats are required by alternative browsers but I suspect there are insufficient offline users on these browsers to warrant precaching the resources (offline users outside of app and outside of chrome). With the service workers, it is pretty easy to use an alternative caching strategy so they are cached if/when used. 

## NotoSans (1402kb) 

571kB potential savings -- We don't use the Italic or BoldItalic versions. So these seem unnecessary to precache. We can consider to not precache them and make a unit test which confirms we never use `font-style: italic;` and if the test fails, it will remind the dev to just add them back into the cache. 

Follow-up after #5219

**Comment by garethbowen** [comment]
I think we can definitely reduce the font awesome fonts as you say.

I'm not confident that we never use notosans italic - I see a few instances of `font-style: italic` in the built css, mostly in Enketo forms.

If we didn't include the italic fonts then the browser would fake it algorithmically which I suspect is definitely good enough for our use. As part of this issue take a screenshot of the italic font compared to the browser italicising the regular font and run it past @amandacilek for acceptance.

**Comment by Jodge** [comment]
@garethbowen  So after some deep dive, I realized there is only one place that we use **NotoSans Italic** `font-style: italic`  and that is on _missing translations on the admin console_

At no point do we use **Noto's** `font-weight: bold` i.e **NotoSans-Bold.ttf**

Also at no point do we use `font-style: italic, font-weight: bold` **NotoSans-BoldItalic.ttf**

I removed **NotoSans-Italic.ttf** to see how browser calculates the italicising and from the screenshoot below I think the difference is quite noticeable

![image](https://user-images.githubusercontent.com/4542994/54765956-7868dc00-4c0b-11e9-9753-b947f1197825.png)
![image](https://user-images.githubusercontent.com/4542994/54765968-7ef75380-4c0b-11e9-8f2e-7580581d1967.png)

I think we can go this route kenn suggests?
> We don't use the Italic or BoldItalic versions. So these seem unnecessary to precache. We can consider to not precache them and make a unit test which confirms we never use

**Comment by garethbowen** [comment]
Whoa, those fonts are _way_ different - that's not working at all how I'd expect. Did you remember to also update font.less to refer to the right font? I think you just need to remove this block:

```css
@font-face {
  font-family: 'Noto';
  src: url(/fonts/NotoSans-Italic.ttf) format("truetype");
  font-weight: normal;
  font-style: italic;
}
```

**Comment by Jodge** [comment]
Interestingly if I remove that block it now goes for **BoldItalic**

```css
@font-face {
  font-family: 'Noto';
  src: url(/fonts/NotoSans-BoldItalic.ttf) format("truetype");
  font-weight: bold;
  font-style: italic;
}
```

when I get rid of **BoldItalic**, it runs out of option and defaults to the second image I attached earlier

**Comment by amandacilek** [comment]
We do use Italic, basically in forms from what I can tell. I have a widget that lets me see the specs on fonts displayed in a browser though, and oddly, when I go to a form and check the Italic text there, it says that it is Open Sans (probably a default sans serif). All the other text in the form says Noto except for the italic. Any idea why it would be reverting to the default font instead of Noto for the italic?
![Screen Shot 2019-03-22 at 10 41 51 AM](https://user-images.githubusercontent.com/26235957/54842490-49944980-4c8f-11e9-82e0-2fc809c5f84d.png)

I have a few concerns with letting the browser do the italicizing:
- It will never appear exactly as the true "italic" font style does, because what the browser does is just slant the characters (vs real italic which is an entirely different design). See some comparisions here: https://www.smashingmagazine.com/2012/07/avoiding-faux-weights-styles-google-web-fonts/. It makes typographers shudder. I know our users aren't type nerds, but the other potential problem is that:
- The results will vary by browser. We won't be able to predict exactly how the text will display for every user, leading to potential inconsistencies and odd bugs that we don't catch.

**Comment by amandacilek** [comment]
All that being said, I think performance is more important than aesthetics for our users, so if it does really help, I'm fine with the browser italic. Just wanted to share a designer's perspective. :)

**Comment by garethbowen** [comment]
Thanks Amanda. There is another compromise which is to change the styling so we don't use italics anywhere, but that feels like a constraint on future designs. I'll have a play today and see if I can work out how to get slanted Noto and see how that looks.

**Comment by garethbowen** [comment]
I thought there was something weird going on because in your screenshot the italic "a" is quite different from the normal "a", but I checked the font online and that's by design: https://www.google.com/get/noto/#sans-lgc

The "f" is also a very different style. I honestly don't know what they're thinking...

Okay here's what I get...

Regular:

![regular](https://user-images.githubusercontent.com/2064938/54969616-b71fdd00-4fe3-11e9-8ace-ebf1d74e31d8.png)

Italic using the font:

![italic-font](https://user-images.githubusercontent.com/2064938/54969614-b71fdd00-4fe3-11e9-93b8-70d2262d5411.png)

Italic using the browser slanting the regular font:

![italic-slanted](https://user-images.githubusercontent.com/2064938/54969615-b71fdd00-4fe3-11e9-9ec2-a1766336c70f.png)

I actually prefer the browser slanted version because it's more in keeping with the original font. @amandacilek Is the browser slanting option acceptable to you?

**Comment by amandacilek** [comment]
Yeah. Can you please double check that it looks similarly ok across browsers though.

**Comment by garethbowen** [comment]
Above is Chrome. Here is Firefox...

Regular:

![Screenshot from 2019-03-27 08-54-16](https://user-images.githubusercontent.com/2064938/55029171-440f7880-506e-11e9-9a47-f2f621988469.png)

Italic using the font:

![Screenshot from 2019-03-27 08-54-54](https://user-images.githubusercontent.com/2064938/55029179-4c67b380-506e-11e9-873f-b44ced6bf861.png)

Italic using the browser slanting the regular font:

![Screenshot from 2019-03-27 08-56-18](https://user-images.githubusercontent.com/2064938/55029184-512c6780-506e-11e9-85e8-2eaf2e678f25.png)

Looks very similar to the Chrome results to me.

We only support Firefox and Chrome so that's all the browsers covered. I only tested on Linux and it's likely it'll look a little different on different OSes but it should look mostly the same.

@amandacilek Does that work for you?

**Comment by amandacilek** [comment]
Yep both look ok, thanks.

**Comment by Jodge** [comment]
Ready form `AT` on branch `5260-font-cache`

Basically testing to see the browser Cache storage size before and after this change, my preliminary test shows it has reduced by _2.4MB_

**Comment by ngaruko** [comment]
![image](https://user-images.githubusercontent.com/6979995/56649280-7cb26a00-668d-11e9-9cc4-b185a54cd772.png)

![image](https://user-images.githubusercontent.com/6979995/56651007-d36d7300-6690-11e9-9a0e-85d62273865e.png)

after clear site data
![image](https://user-images.githubusercontent.com/6979995/56651052-e8e29d00-6690-11e9-953b-6187538c7cdf.png)

reloaded
![image](https://user-images.githubusercontent.com/6979995/56651106-057ed500-6691-11e9-8382-4879e2dde918.png)

on the branch --
![image](https://user-images.githubusercontent.com/6979995/56654236-44fcef80-6698-11e9-9f1d-0517093f347a.png)

**Comment by kennsippell** [comment]
@ngaruko @Jodge  I just ran the following test on latest master:

* Login as offline user
* Go offline
* Refresh the page

Expected: Fonts load
Observed: No fonts

**Comment by kennsippell** [comment]
I included the fix for this in #5557.

**Comment by newtewt** [comment]
@kennsippell  I'm using master(installed a few minutes ago through horti) on my local instance and the fonts seem to be loading. Can you expand on what you were seeing?

**Comment by kennsippell** [comment]
@newtewt If you look at the list of resources in the cache there are no fonts:
![Screenshot from 2019-05-01 08-16-28](https://user-images.githubusercontent.com/9014751/57024495-9a318780-6be9-11e9-9978-30c943f2c4b8.png)

As an offline user, I'm seeing a 404 for the request to `http://localhost:5988/fonts/NotoSans-Regular.ttf` and I'm seeing rectangles instead of font-awesome decals.

**Comment by ngaruko** [comment]
LGTM atm. Thanks @kennsippell for spotting and fixing that.
