### ISSUE TITLE
Translations not updated after upgrade

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5271]
Discovered after `gamma.dev` was upgraded from 3.2.1 to master (3.4.x) . 
Instead of using translations that were correctly deployed with the new 3.4 ddoc, the app ended up using it's previous translations. 

This is caused by the `convert-translation-messages` running after merging translations,  causing the old `values` be copied over the new `generic` translations.

**Comment by wtekeu** [comment]
@dianabarsan  So, my understanding is that this is due to the fact that post merging we are in a state where we have both `values` and `generic`. Please confirm that this is the case. Then I think an easy fix is not updating `generic` during  the execution of `convert-translation-messages` (the merging would have taken care of it)

**Comment by ngaruko** [comment]
LGTM.
Tested on latest master
