### ISSUE TITLE
Upgrades via admin upgrade page are broken

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5277]
1. Login to `gamma.dev` as admin
1. Navigate to admin console
1. Click "Upgrade Instance"
1. Attempt an Upgrade

Expected: Upgrade
Observed: Error `Refused to connect to 'https://staging.dev.medicmobile.org/_couch/builds/' because it violates the following Security-Content-Policy directory: "connect-src: 'self'"`

![image](https://user-images.githubusercontent.com/9014751/51635998-28ea9480-1f69-11e9-9b5f-94e1c0c7e5ab.png)

**Comment by garethbowen** [comment]
Commit: https://github.com/medic/medic-webapp/commit/754590c27329ac2a655ebc221fcfae446cd0a62b

**Comment by dianabarsan** [comment]
I am also seeing this:
![image](https://user-images.githubusercontent.com/35681649/51666345-4863da80-1fc6-11e9-9de3-914fe03edb08.png)

```
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' 'sha256-6i0jYw/zxQO6q9fIxqI++wftTrPWB3yxt4tQqy6By6k=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
```

When trying to click the `Reload application` button after an upgrade.

**Comment by ngaruko** [comment]
The original issue is resolved, but I still see this when updating @kennsippell . If it  is not related, I will close this and open a different issue
![image](https://user-images.githubusercontent.com/6979995/52453474-76434480-2bac-11e9-90f4-1dbdfcd57c96.png)

**Comment by SCdF** [comment]
@ngaruko what are you doing when you get this error?

**Comment by ngaruko** [comment]
@SCdF Just logging in as admin, go to the admin portal and click `Upgrade instance`.
On `gamma.dev` (running 3.3.x), you get this
![image](https://user-images.githubusercontent.com/6979995/52675909-2a6a1400-2f8d-11e9-8dcb-382d807d000c.png)

and on local (running latest master atm 3.5):
![image](https://user-images.githubusercontent.com/6979995/52675988-6ac99200-2f8d-11e9-9d90-87f6c3355774.png)

**Comment by SCdF** [comment]
@ngaruko I'm dropping this to low priority because AFAICT this should affect the ability to perform an upgrade, and is only a visual bug that causes an icon to not appear in a view only seen by development builds.

If it is causing upgrading to not work please change it back to high priority and let me know.

What is happening here is some refactor / merge / whatever has caused us to be looking for the `base_version` property where it doesn't exist. This means that in development systems (not production ones), we aren't able to provide a guess as to whether a branch build might be compatible with your existing build. The upshot being: there is no little warning icon appearing beside branches that might be incompatible compared to this version.

I can look into this a little later, but probably not in the next few days, and I don't think it should get in the way of a release.

**Comment by garethbowen** [comment]
@SCdF I think what @ngaruko found is a completely separate issue. Do you agree Bede?

If so, could you raise a new issue for the one you found and I'll triage it, and then if the original issue is fixed (which it looks like it is) close this one?

**Comment by ngaruko** [comment]
Thanks @SCdF . I agree with you: this is a minor issue that shouldn't get in the way of a release. Indeed, I will close this and raise the console error issue differently, if needed...
