### ISSUE TITLE
The conditional_alerts transition should sort docs by reported_date

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5357]
Because sorting reports is broken, conditions that compare multiple reports and depend on these reports to be sorted chronologically can randomly fail when they shouldn't.

**Comment by garethbowen** [comment]
I was about to pass this but I've found an annoying bug that I think we should consider patching as well as the sorting being broken... I've configured an alert to fire if the most recent report matches a pattern (eg: `P(0).fields.last_menstrual_period == 5`). Then if I submit a P with LMP of 5 this adds the alert as expected. If I _then_ submit a P with LMP of 10 it adds the alert again. This is because the transition fires before the doc is saved so the first time through the most recent report is the _previous_ report, not the current one, so the condition matches. The original report also failed the condition because there were no previous reports, but then other transitions run, the doc is saved, which causes the conditional alerts transition to run again, this time finding the current doc and correctly adding the alert.

I think we should change the logic of conditional alerts so it includes the current report in the array of docs to check. This would solve the incorrect case, and mean the correct case succeeds the first time through.

@dianabarsan What do you think?

**Comment by dianabarsan** [comment]
Oh yea, absolutely.

**Comment by garethbowen** [comment]
I'm on it!

**Comment by garethbowen** [comment]
I've raised this as a new bug: #5668

Closing this one as the ordering worked perfectly!
