### ISSUE TITLE
Registration transition should calculate dates relative to reported_date

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5410]
Currently, `registration` transition calculates three dates:
a. date of birth
b. last menstrual period
c. expected birth date

https://github.com/medic/medic/blob/3d4f54ec5772fc2bcc4f77c68d0e4ab26ad0ebf8/sentinel/src/transitions/registration.js#L221
https://github.com/medic/medic/blob/3d4f54ec5772fc2bcc4f77c68d0e4ab26ad0ebf8/sentinel/src/transitions/registration.js#L155

All of these dates are calculated in reference to the moment Sentinel processes the doc instead of (what seems logical to me) the doc's `reported_date`.

In an ideal world, Sentinel would never crash, never be misconfigured and should always process all docs in a timely manner. Sadly.... 

@abbyad @garethbowen I'm not sure if this is a bug or working as intended.

**Comment by garethbowen** [comment]
I think you're right, this is a bug. SMS messages in particular should be based of the `reported_date` just in case sentinel gets behind.

The only reason I can think of that this would be wrong is if someone is using the registration transition with enketo forms because we know that CHW phones often have an incorrect date. I'm fairly sure nobody would ever use this transition with enketo forms, but it's the only issue I can think of!

**Comment by ngaruko** [comment]
LGTM
