### ISSUE TITLE
Error loading permissions

### ISSUE THREAD

**Issue by ngaruko** [medic/medic#5452]
**Steps to reproduce**:
 - _Log in to the admin console/app settings_
 - _Click on `Roles & permissions`_
 

**What should happen**:
 - _`Roles & permissions` page should display with defaults Roles & permissions_

**What actually happens**:
 - _The  permissions tab comes blank with some errors in the console_
 _```Error fetching settings TypeError: roles.includes is not a function
    at main.js:104714
    at Array.map (<anonymous>)
    at makeRoleModel (main.js:104711)
    at main.js:104730
    at Array.forEach (<anonymous>)
    at main.js:104727
    at processQueue (main.js:37529)
    at main.js:37577
    at Scope.$digest (main.js:38690)
    at Scope.$apply (main.js:39078)
(anonymous) @ main.js:35151```_

![image](https://user-images.githubusercontent.com/6979995/53306930-fdf0b900-38f7-11e9-9257-572df8bdda36.png)

**Environment**:

- Instance: _(gamma.dev.medicmobile.org)_
- Browser: _(Firefox, Chrome)_
- Client platform: _(MacOS)_
- App: _(webapp, admin)_
- Version: _(3.4)_

Makes in impossible for restricted users to login
![image](https://user-images.githubusercontent.com/6979995/53306952-4019fa80-38f8-11e9-9f12-3eb08066845d.png)

**Comment by garethbowen** [comment]
This is a configuration issue - somehow this server has 3.3.x era configuration with 3.4.x code. I'm guessing you've gone back and forwards between versions and that has broken the configuration. This would be caused by, for example, upgrading to 3.4, downgrading to 3.3, installing 3.3 config, then upgrading to 3.4.

We have a migration to fix this and we should check that it's working as expected.

The workaround for now is to upload the 3.4.x version of the config.

**Comment by garethbowen** [comment]
Removed from the release until it's been verified as a bug.

**Comment by garethbowen** [comment]
@ngaruko Can you confirm whether or not this is a bug?

**Comment by garethbowen** [comment]
No response from @ngaruko - closing as can't reproduce.
