### ISSUE TITLE
Performance regression when loading reports

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5455]
First discovered in [performance testing for the 3.3.0 release](https://docs.google.com/document/d/1ab_wjxsT9millrBAy3SjZxWBT8KRmBElBuwgz9XAGII/edit?pli=1#heading=h.jqsljlq9vrt8) loading a report has regressed from previous versions. It was decided that it wasn't a blocker for release but we should revisit it soon to see if any improvements can be made.

**Comment by garethbowen** [comment]
The only relevant code change I can find is to do with linking from the report patient fields to the patient so I'll start investigating there.

**Comment by garethbowen** [comment]
Ready for AT. Install the branch `5455-report-content-loading-performance` and compare the performance against `3.4.0` or above.

**Comment by wtekeu** [comment]
LGTM.

Performed performance testing using the following setup: https://docs.google.com/document/d/1ab_wjxsT9millrBAy3SjZxWBT8KRmBElBuwgz9XAGII/edit?pli=1# and measuring the time it took for the reports page to load after clicking on the reports tab

branch `3.4.0`:
loading reports: 1015 ms, 1030 ms, 961 ms => average: **1002 ms**

branch `5455-report-content-loading-performance`:
loading reports: 786 ms, 685 ms, 726 ms => average: **732 ms**

Not merged because of conflicts

Back to you @garethbowen

**Comment by garethbowen** [comment]
Reopening so merging doesn't get missed.

**Comment by garethbowen** [comment]
Merged to `master`.
