### ISSUE TITLE
Add new permissions to allow users to view outgoing messages and export tabs of the admin app

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5464]
In a call with @smbuthia  we were discussing who can view the outgoing messages tab. There was a request from a project to make this visible to users that are not able to configure the app. Creating to discuss if this page would be viable for the use case or possibly something else added.  [Reference to the original ticket for outgoing messages. ](https://github.com/medic/medic/issues/649)

**Comment by garethbowen** [comment]
@newtewt It only makes sense for online users obviously. Would it make sense to leave it in the admin app, but have a permission which lets you see the outgoing messages tab and nothing else? These users could probably get access to the Export tab too.

**Comment by newtewt** [comment]
@garethbowen  I am asking @smbuthia  to provide more details here to better represent the request from partners.

**Comment by smbuthia** [comment]
@garethbowen @newtewt yes, those who would like to see the messages are online users. Enabling them to see the messages and export tab and nothing else would work. The main concern was them having access to configs etc

**Comment by garethbowen** [comment]
@amandacilek What do you think about this? Would it make sense to have some users see a restricted view of the "admin" app which just shows Outgoing Messages and Export?

**Comment by amandacilek** [comment]
Hm, @simbuthia could you please explain more about the use case for these users? 
- Who are the users requesting access? Are they managers in a field office or nurses in a health facility (or some other sort of leadership role)? 
- Why do they want to look at the outgoing messages page, and what data in particular are they interested in there?
- Any idea how frequently they might visit this page if they had it?

@garethbowen I think that sounds ok, at least for now. As long as the users seeing the restricted view are still some sort of administrative-level role (and not CHWs).

**Comment by smbuthia** [comment]
@amandacilek 
> Who are the users requesting access? Are they managers in a field office or nurses in a health facility (or some other sort of leadership role)?

- Facility supervisors and nurses (with online accounts), program admins (these are partner level managers), and field officers (Medic Mobile staff and Partner staff).

> Why do they want to look at the outgoing messages page, and what data in particular are they interested in there?

- For nurses to track upcoming appointments and plan for visits in advance. They would be interested in the sent message and date the message went out (or was due).
- For facility supervisors to follow up with field supervisors on any missed appointments (by checking messages that were sent out on missed appointments). They would be interested in the message, the recipient, and the date the message went out.
- For program admins and field officers to monitor outgoing messages. They would be interested in the message, the recipient and the status.

> Any idea how frequently they might visit this page if they had it?

- At least weekly.

**Comment by amandacilek** [comment]
Thanks for the extra info @smbuthia! This page was not specifically designed for all of the use cases you mention, but like I said, I'm fine if our solution for now is to give some users a restricted view of the "admin" app. @garethbowen Is this ticket assigned to me because you all are just waiting to hear further thoughts from me?  

Long term, we'd probably want to consider ways to add support for these use cases in the app itself. 
- We've had requests to add a list of upcoming appointments before, but, this is categorized as a "nurse" workflow, and the product team has decided to focus on supporting CHWs and supervisors first. In this case, adding this feature to the app for nurses is probably a ways out, so I suppose the interim workaround of using the outgoing messages page is better than nothing.
- For the missed appointments, can we generate a task for the missed appointment, and send that task to the facility supervisor? Or are they "admin" roles for whom tasks are disabled? If the latter, again it does make sense to use the outgoing messages page lacking anything else.

I'd say go ahead and proceed with the plan that Gareth mentioned.

Worth noting: For both of the above use cases, I think we could improve the workflow and utility of the outgoing message page by adding in filter/sort/search functionality. We were always planning to add this functionality at some point... curious what you think @garethbowen about whether this is something we could get scheduled.

**Comment by garethbowen** [comment]
Ok, let's schedule the simple change of adding new permission(s) so some users can access only export and/or outgoing messages pages and nothing else. It's a quick fix and sounds like it would be useful for certain users.

@amandacilek Can you raise new issues for specific changes that would help those workflows? That'll get them into the prioritisation hopper.

**Comment by garethbowen** [comment]
Ready for AT in `5464-outgoing-messages`.

**Comment by garethbowen** [comment]
AT passed. Merged.

**Comment by ngaruko** [comment]
Currently, when `can_view_outgoing_messages` is selected for restricted user, the user can see the `App Settings` link, but does not actually have permission to the `admin` page. It would be expected that the user would have access to the page with only the allowed permission showing, in this case the `Outgoing messages`. I am reopening this for better traceability, instead of creating a new issue.
![image](https://user-images.githubusercontent.com/6979995/60555252-f3f03280-9d8f-11e9-960a-9d21cca5fde2.png)
Assigning it back to you @garethbowen , since @Jodge is not around!

**Comment by garethbowen** [comment]
@ngaruko Can you please tell me if that user's role is online or offline? Also which of these three permissions (if any) does the user have: `can_configure`, `can_view_outgoing_messages`, `can_export_all`?

**Comment by ngaruko** [comment]
@garethbowen The user role is `offline` only the `can_view_outgoing_messages` permission is selected, `can_configure` and `can_export_all` are off.

**Comment by dianabarsan** [comment]
Ready for AT on `5464-race-condition-in-auth-options`

**Comment by newtewt** [comment]
Is `can_view_outgoing_messages` the only permission that needs to be selected to see the outgoing messages in the admin app? IS this restricted to offline or online?

**Comment by dianabarsan** [comment]
It should be restricted to online only. Offline users should not be able to access admin app at all. 
I think `can_view_outgoing_messages` for an online user should be enough to access the admin app -> outgoing messages.

**Comment by dianabarsan** [comment]
As far as I can tell, if you *don't* have `can_view_outgoing_messages` but have `can_configure`, you're not able to view the outgoing messages tab, is that correct?

**Comment by newtewt** [comment]
I just tested that and it works as you described. Based on the way @ngaruko  wrote the issue. I thought maybe this should work for offline users as well.

**Comment by newtewt** [comment]
Cool, after confirming with @ngaruko  I'm closing this. Offline users cannot access outgoing messages even with permission and they no longer see the app settings option in the menu. While online users that do have that specific permission can.

**Comment by garethbowen** [comment]
The App Settings link should only show if you're on Desktop, an online user, *and* have one or more of these permissions; `can_configure`, `can_view_outgoing_messages`, or `can_export_all`.

We decided it would be too confusing to show the link to offline users for whom it will not work most of the time.
