### ISSUE TITLE
Add ability to configure colors on medic web app

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5533]
In 3.4 we added the ability to do some branding for the header logo. @nomulex  @smbuthia asked during our 3.4 release training call about possibly making the colors of the webapp or at the very least the header configurable to match more in line with our partner's logos.  Another possibility would be for maybe a design member(@amandacilek) to work the logo colors to our colors. Either way we wanted to open an issue for discussion about this.

**Comment by amandacilek** [comment]
Hey there. Thanks for raising this question.

We discussed this possibility in the past and were not keen on allowing customization of the app colors at this time for a few reasons. I'll split up app colors into three categories and respond to each individually. cc @abbyad @garethbowen @diannakane 

**The colors of the header bars**
Currently we have two bars - the dark grey bar at the very top that contains the logo and the navigation, and a secondary bar below that varies color depending on page tab and is either blank or contains filters. We use color as a wayfinding device to help indicate which page of the app the user is on. Thus, the very top bar is a neutral grey since this bar is present on every page. If we allowed partners to customize the dark grey bar to whatever color they desired, this would not only look visually jarring, but it could confuse the meaning of color in the app (if the top bar is customized to blue, would it look like every page was the Tasks page at first glance? if the top bar is customized to red, would it look like every page has an error? Lots to think about).

Once we implement the navigation redesign, there will only be one bar (not two stacked bars) and the color of this bar will change depending on what page the user is on. Allowing customization would also be tricky then, as partners would either have to choose multiple custom colors, or choose one single color and lose the variation from page to page.

This topic is something worth considering further. Perhaps one day we will support custom header colors, but I do not recommend both custom colors and different colors for each tab. I think we have to choose. Either the app has _one_ main app color (no variation between pages) and we allow that main color to be customized, or the app retains the individual colors for each page, in which case we do not offer customization for the header colors. Requires further discussion amongst the product team.


**The colors of main content UI elements**
In my opinion, we should never allow customization of the coloring of app primary content or UI elements. We have chosen these colors for a reason, because they either enhance legibility, or add to the understanding of the UI and enhance meaning, and changing them would cause confusion.

A few examples:
- Text links are styled blue. This is because blue is a common UI pattern to indicate something that is clickable.
- New messages and reports are marked with blue. Marking them in a different color, such as orange or yellow, could make it appear like we are highlighting errors instead of newness.
- On the reports tab, we use red and green to indicate messages that have either been verified as correct or marked as having errors. This is another common UI pattern and universal interpretation of color - red for bad, green for good.
- Same thing with the Targets page - we intentionally use red and green to indicate poor or good performance. 


**The colors of the icons**
Icons are used throughout the app to aid in visual comprehension. Right now the icons are colorful, and their colors were chosen to enhance understanding, but there is some degree of arbitrariness. We have suggestions for which colors to display the icons in but I do not think of these colors as hard rules that partners must follow. We already allow partners to upload their own custom logos so technically it is already within their power to make the icons whatever color they like - it is beyond our control to regulate them.

**Comment by amandacilek** [comment]
> Another possibility would be for maybe a design member(@amandacilek) to work the logo colors to our colors.

Forgot to respond to this part. Is someone asking for a designer to potentially help them style their logo so that it works well in the Medic app? I would be happy to assist, however, I think we should limit assistance to Medic's closest model building partners and other large deployments like MOH. I do not think we want to take on the responsibility for assisting with every single white labeling need as it would be a big time commitment.

**Comment by smbuthia** [comment]
@amandacilek for my part, the query came mostly as pre-emption of what a partner might ask. I think the response above will help respond to such queries. Thanks.

**Comment by garethbowen** [comment]
Closing this as it's not something we want to support in the near future. Please reopen if it becomes a requirement.
