### ISSUE TITLE
Add a permission to show the Report edit button

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5537]
On the Report/History tab there's a button to edit a report which is shown to all users but sometimes we don't want certain users to be able to edit reports. Add a permission to the default and standard configurations that is required to allow for editing of reports. By default all roles should have this permission.

Requested by @Fatoufall in https://github.com/medic/medic-projects/issues/6057

**Comment by kennsippell** [comment]
Instead of solving this with user-level permissions, another way to handle this requirement might be that documents cannot be edited if the document is replicated due to the `needs_signoff` property.  

We can semantically infer from the needs_signoff property that this user isn't the owner or creator of the document and thus has no business editing or altering it. But they can still edit their own documents (for example, Muso's supervisor calendar).

**Comment by dianabarsan** [comment]
I think adding a user permission is a clearer and more complete solution for this, it can also be applied for other cases, not just this specific one.

**Comment by garethbowen** [comment]
Ready for AT in `5537-can-edit-reports`

**Comment by dianabarsan** [comment]
For AT, I've also updated some code around restricting access to certain routes, so please make sure that still works as expected (https://github.com/medic/medic/issues/4711).

**Comment by ngaruko** [comment]
LGTM @dianabarsan 
Also checked access restrictions when the roles are not on the account.
![image](https://user-images.githubusercontent.com/6979995/55532696-58f1a900-570b-11e9-8ec3-5d3f951c6c15.png)
