### ISSUE TITLE
Profile application memory usage

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5540]
I think our application uses too much memory. The primary suspect is nools which stores every report and contact in memory.

Log in as an offline user with at least 10,000 docs and measure memory usage once the app has started. Assuming we do indeed use too much memory, do some investigation into where the memory is being used. You may need to hack out parts of the app in order to work this out. Document your results as well as whatever process you used.

**Comment by garethbowen** [comment]
@MaxDiz I'd like to schedule this for 3.6.0. It's a reasonable amount of work but could lead to some significant performance improvements for later releases.

**Comment by MaxDiz** [comment]
Good call. This is a key issue to app stability and scalability and our 'doc limit policy' for users isn't a legit fix. We have a bunch of app & server side analytics/telemetry improvements under consideration. If your exploration reveals any ongoing needs, we can re-prioritize

**Comment by kennsippell** [comment]
## WebApp Client-Side Memory Profiling

### Android Memory Profiling

**How much memory should we use according to Android?**
* Testing on my Tecno F1
* Android 8.0
* 1GB Ram - 460MB available on clean boot

Function | Result | Summary of Meaning
-- | -- | --
[Runtime.maxMemory](https://developer.android.com/reference/java/lang/Runtime#maxMemory()) | 134 MB | Returns the maximum amount of memory that the Java virtual machine will attempt to use.
ActivityManager.getMemoryClass | 128 MB | This gives you an idea of how hard a memory limit you should impose on your application to let the overall system work best.
[ActivityManager.getLargeMemoryClass](https://developer.android.com/reference/android/app/ActivityManager.html#getLargeMemoryClass()) | 256 MB | Return the approximate per-application memory class of the current device when an application is running with a large heap.
[MemoryInfo.threshold](https://developer.android.com/reference/android/app/ActivityManager.MemoryInfo#threshold) | 144 MB | The threshold of availMem at which [android] considers memory to be low and start killing background services and other non-extraneous processes.

**How much memory does medic-android use?**
For this I’m using:

- The unbranded flavor of medic-android
- Master branch of medic 
- Deployment of standard 
- Seed data used for performance testing
- adb shell dumpsys meminfo org.medicmobile.webapp.mobile
- Not able to force a Java GC, so numbers are noisy
- Measure is Total Proportional Set Size PSS


Scenario | Total PSS
-- | --
Initial unbranded screen to select domain | 16.1M20.3M
Login page | 162.0M160M
After loading “empty” user (45 docs) | 165.2M
After loading “typical” user (ac1 with 1850 docs) | 275.7M
After loading “stress” user(habibayo with 9029 docs) | ?

### Chrome Memory Profiling
Testing to be performed on:

- Master branch with altered grunt file so dev build removes sourceMaps but doesn’t minify so I can understand the profiles
- Deployment of standard configuration
- Incognito window 
- Standard seed data for performance testing
- Chrome 75

**What is Chrome’s maximum heap size for a tab?**

Running the webapp in Chrome 75 on the Tecno F1, I sometimes see a dialog reporting “This page uses too much memory, so Chrome removed some content” and the page fails to load. Isolating Chrome’s limit for my Tecno F1, it has a hard cap for heap allocations at 50MB.

**Chrome’s Heap Size**
Measurements taken after forcing a GC.


Scenario | Chrome 75 Ubuntu Desktop | Medic-AndroidAndroid 8 | Android 8 Chrome 75 App
-- | -- | -- | --
Login page | 5.0 | 4.3* | 6.7
After loading “empty” user (45 docs) | 38.3 | 14.8* | 16.8
After loading “typical” user (ac1 with 1850 docs) | 53.1 | 25.4* | 26.9
After loading “stress” user(habibayo with 9029 docs) | 158 | 120 ** |  

 * I’m unable to get these numbers directly from the debugger. Chrome crashes if I take a heap profile (on two machines). Chrome’s window.performance.memory object via console has quantized numbers. Reports numbers are estimations from a timeline recording.
 ** Attempts to measure on Tecno F1 were inhibited by DOMException: Failed to execute 'transaction' on 'IDBDatabase'. Measure is the highest confirmed measure before crash. 

**Heap profile for “empty user”**
Memory profile from:

- Loading “empty” user (45 docs)
- Android 8 Tecno F1
- Chrome 75 (has better profiler than Chrome 53)

My notes:

- Profile reports heap size at 9.6MB even though performance monitor reported 16.8MB
- Largest single object is the google-libphonenumber library (1.6MB)
- Two retained copies of the settings document (~200kb). But this can sometimes contain some very large strings.
- 200kb translation strings
- 500kb loaded modules via require
- 3.3MB of “compiled code”


**Heap profile for “typical user”**
Memory profile from:

- Loading “typical user” (ac1 with 1850 docs)
- Android 8 Tecno F1
- Chrome 75 (has better profiler than Chrome 53)

My notes:

- Reports heap as 19.0MB but performance monitor reported 22.1
- Very large inputs from nools (see below)
- Target emissions coming out of nools (0.5MB)
- Again, two copies of the settings doc.

**Looking at high-doc count user**
Testing on:

- Documents replicated from muso-mali.app user habibayo (webapp 3.6)
- Production muso configuration deployed
- Master branch with altered grunt file to remove sourceMaps
- Incognito window
- Chrome 75

15,409 docs for this user replicated to CouchDB (81.6MB in CouchDB) 
9,029 in PouchDB after purge (95.6 MB in IndexedDB)
56MB Chrome’s heap before call to search in RulesEngine
148MB after rule’s engine search 
158MB after copying into Nools 

Conclude that for this user, 104 MB of 158MB total heap (68% of heap) is for retained Nools inputs

## Suggestions

- XWalk has about a 150MB overhead just to load the login page
- Instrumentation (#64)
  - Android’s memory statistics for the device (available memory and low-memory threshold)
  - Capture any Android onLowMemory and onTrimMemory(int) events
  - Chrome’s window.performance.memory values are quantized but maybe still useful order-of-magnitude numbers
- We may benefit from enabling [largeHeap](https://developer.android.com/guide/topics/manifest/application-element) setting in the android manifest since our general footprint is large. (#88)
- For some users in production, our RulesEngine code retains >100MB of contact/report data (68% of total retained heap). (#5657)
- Target emissions from Nools are also retained (0.5 - 1MB measured cost for this sample user without many targets). I made some suggestions for optimizing this at https://github.com/medic/medic/issues/5515.
- Should we hold the loaded google-libphonenumber library in memory at all times? Can reduce our base JavaScript heap by ~20% if not.
