### ISSUE TITLE
Move "selected" into redux store

### ISSUE THREAD

**Issue by rmhowe** [medic/medic#5546]
As part of the ongoing changes to get ready to [move to Angular 7](https://github.com/medic/medic/issues/4750), this issue is for moving `selected` into the redux store. This is effectively a refactor with no new features added.

**AT**: `selected` refers to the currently selected contact/report/message/etc (ie looking at one in a detailed view on the RHS), and also the situation when multiple reports are selected for bulk actions. Any workflow with a reference to `selected` will need to be checked for regressions.

**Comment by ngaruko** [comment]
Upon selecting a place on the LHS, people in that place seem are also showing as `selected`. Is that intentional @rmhowe ?
_**Previous version**_
![image](https://user-images.githubusercontent.com/6979995/56564384-8e750e00-65b6-11e9-8b45-db0246d56e25.png)
![image](https://user-images.githubusercontent.com/6979995/56564436-a8aeec00-65b6-11e9-87ea-2e51295ef9af.png)

**_This version_**

**Comment by rmhowe** [comment]
@ngaruko not intentional! Pushed a fix to the branch, should be working fine now.

**Comment by ngaruko** [comment]
LGTM ATM . 
Thanks @rmhowe . Merging.
![image](https://user-images.githubusercontent.com/6979995/57264571-bee49e00-70c6-11e9-9da5-6549216304fd.png)
