### ISSUE TITLE
Loading portions of the reports tab causes the page to lock up.

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5724]
**Describe the bug**
Selecting check boxes from the drop downs on the reports tab will show the chrome wait for page to become responsive or exit page modal. It is around the 2:37 mark in the linked video. 

https://github.com/medic/medic/issues/4423#issuecomment-501871370

**To Reproduce**
1. Navigate to https://3upgrade-lg.dev.medicmobile.org/admin/#/upgrade
2. Click on reports tab
3. Scroll down to select a parent with a lot of children. 195 were associated to the parent
4. Wait until the page displays the error

**Expected behavior**
Hopefully no page unresponsive error can be displayed and we load a bit faster. 

**Logs**
If applicable, include the server or browser logs.

**Screenshots**

**Environment**
- Instance: 4423-improve-performance-of-reports-loading 
- Browser: Chrome
- Client platform: Ubuntu
- App:  webapp
- Version: Branch was based on 3.5 but exists in earlier versions. 

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by garethbowen** [comment]
@newtewt I presume this is an online user?

**Comment by garethbowen** [comment]
I think the problem here is we query a view passing in all 195 IDs. In this specific case it's unnecessary - if you select a parent the all the reports for the children will already be included. Therefore we can make a reasonably easy optimisation to not include the child IDs if all of the children are selected. This is probably the most common case.

I think this also indicates we have a bug - if you select all children then deselect one not only will the performance be bad but you will still get reports for the deselected child. This is a less common case but I think we should correct it regardless. There are two ways I can think of to fix this:
1. If you deselect a child then we should also deselect the parent. This will still give terrible performance (searching for 193 contacts in this case) but will be correct.
2. Don't allow users to deselect a child if the parent is selected. It doesn't seem likely that people would want to search for reports from most of the children of a place. People could still manually check 193 children from this place and get terrible performance but that seems really unlikely.

I think my preferred option is #2 . @amandacilek Does that seem reasonable to you?

**Comment by amandacilek** [comment]
Is this in relation to checkboxes in a filter dropdown? Yeah #1 sounds like a weird UX (that deselecting one subsidiary thing deselects the higher level parent thing). #2 sounds a little better. If the user isn't allowed to select/deselect a child item though, maybe we should make the checkmark visually different to indicate that. Could the child icon still be a checkmark (because it's included in the results) but a grey color to indicate it's not actionable/selectable? Or, could we remove the checkmark icon altogether in front of the children in that case?

**Comment by garethbowen** [comment]
Yes the styling would need to be updated to make it clear.

Let's go with Option 2 so it's obvious that if you select a health_center then all clinics will also be implicitly selected. Then we can implement the performance improvement to not include the clinic IDs in the query, which I _think_ will make this much faster (before and after benchmarks required).

**Comment by SCdF** [comment]
Ready for AT

**Comment by newtewt** [comment]
Waiting for https://github.com/medic/medic-projects/issues/6754 to be finished to test with the same amount of data that was causing the issue.

**Comment by newtewt** [comment]
Looks good. Tested out on the large instance and I cannot unselect children when parents are selected. Also, no wait message.
