### ISSUE TITLE
get_users_meta_docs outputs `[]` as next value forever when there are no docs available to view

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5852]
I'm trying to get the telemetry docs from Muso production data:

`node scripts/get_users_meta_docs.js --mode interactive --type telemetry https://admin:abcd@muso-mali.app.medicmobile.org/medic-users-meta`

I just see `undefined` for every "next" value. Going through all data there is nothing defined.  Selecting "Save all in working directory" results in a file with `[]`.

**Comment by SCdF** [comment]
@kennsippell have you tried looking for telemetry docs yourself? I think they deployed a version that contained telemetry inside this month, which means none would have been generated yet (that will happen starting tomorrow, give or take how long it takes things to eventually sync)

**Comment by wtekeu** [comment]
@kennsippell the db `medic-users-meta` does not exist. In order to have all the telemetry and feedback docs replicated to his db (from the `medic-user-<username>-meta` dbs), the TL need to configure [`replications`](https://github.com/medic/medic-docs/blob/b4f80ac65466eabe38eec73b1e24bdf378e0d266/configuration/app-settings.md#replications). Please @senseibara confirm but I don't think it is the case.

Also, I have looked at the 455  `medic-user-<username>-meta` dbs and they don't have telemetry docs as noted by @SCdF in the comment above.

**Comment by kennsippell** [comment]
Muso-mali upgrade to 3.5 on July 8.  So you're right that there are no telemetry docs until tonight.

For this case, should this script output "undefined" forever when you select `❯ Display next`? Seem like it should just output something like "no documents available". Or "Displaying 0 of 0" and the "next" button shouldn't be available?

**Comment by kennsippell** [comment]
@wtekeu `medic-users-meta` does exist and contains hundreds of thousands of feedback docs.

**Comment by kennsippell** [comment]
@wtekeu This is muso's `replications` configuration from [here](https://muso-mali.app.medicmobile.org/_utils/#database/medic/settings).

```
    "replications": [
      {
        "fromSuffix": "user-[^\\-]+-meta",
        "toSuffix": "users-meta",
        "text_expression": "",
        "cron": "0 2 * * *"
      }
    ],
```

**Comment by wtekeu** [comment]
@kennsippell ok, I can see it as well. Yes, the issue reflected in the new title should be fixed.

**Comment by wtekeu** [comment]
Fixed and merged
