### ISSUE TITLE
Online users have a sync status in the hamburger menu

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5930]
**Describe the bug**
Online users show a sync status in the hamburger menu. When clicking sync now it disapears to only show again when you refresh the page. 

**To Reproduce**
1. Log in as admin
2. Click the hamburger menu in top right. 
3. The sync status is shown to the user. 

**Expected behavior**
Online users should not see the sync status

**Environment**
- Instance: loclahost
- Browser: Chrome
- Client platform: Linux
- App: webapp
- Version: 3.7

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by dianabarsan** [comment]
This looks like it's been caused by https://github.com/medic/medic/commit/198f32697e0804ae144f5946ab3d021dc23f6d00 , specifically by this added delay: https://github.com/medic/medic/blob/master/webapp/src/js/controllers/inbox.js#L63
and the fact that, by default, we consider replication to be enabled (https://github.com/medic/medic/blob/master/webapp/src/js/controllers/inbox.js#L146). 

@newtewt if you refresh the page as an online user, open the hamburger menu and count to 10, does the "sync status" disappear?

**Comment by newtewt** [comment]
@dianabarsan it sure does disappear after 10 seconds.

**Comment by garethbowen** [comment]
Ready for AT in `5930-check-dbsync-isenabled-immediately`

**Comment by newtewt** [comment]
No longer seeing the sync for online users. Only offline.
