### ISSUE TITLE
Transitions missing from default config. 

### ISSUE THREAD

**Issue by newtewt** [medic/medic#6017]
**Describe the bug**
The default config has no transistions configured in app_settings. These are needed for death reporting, patient_id, and more 

**Expected behavior**
config/deafult/app_settings needs transitions added that are required for the config.

**Comment by abbyad** [comment]
Included in 3.7.0 project in case there is an opportunity to include and test using the config before release. Otherwise can wait until next release.

**Comment by dianabarsan** [comment]
Unfortunately, adding `transitions` to the default config (specifically `generate_patient_id_on_people`) is making a lot of our e2e tests to fail. The quick fix would be to disable them for e2e tests for `3.7` and revise them for next release. Otherwise, we can spend the time to revise them in `3.7`.

**Comment by abbyad** [comment]
That's unfortunate, but disabling in 3.7 and fixing in next release seems like the right approach.

**Comment by dianabarsan** [comment]
Merged into `master` and backported to `3.7.x`

**Comment by newtewt** [comment]
I'm seeing the transitions in the latest beta with CHT as default config.
